---
dsh_version: v0.1.1-rc.2
dsh_cache_key: "{{ dsh_version }}:pnpm-{{ pnpm_version }}:node-pty-build"
dsh_cache_version_file: "{{ dsh_state_dir }}/CACHED_VERSION"
dsh_pnpm_dlx_cache_dir: "{{ dsh_home }}/.cache/pnpm/dlx"
dsh_web_plugins: []
dsh_web_plugins_to_remove: []
